version: '3'

services:
  app:
    build: .
    container_name: challenge_api
    depends_on:
      - database
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
  database:
    image: postgres
    container_name: challenge_db
    restart: always
    tty: true
    ports:
      - 65432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=challenge
      - POSTGRES_DB=ton_api
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
